banner:
  title: Security
  subtitle: Open Distro for Elasticsearch
  content: Secures your cluster with a comprehensive set of advanced security features including authentication options via LDAP/Active Directory, Kerberos, SAML and JSON web tokens, encryption in-flight, fine-grained index, document and field-level access control, detailed audit logging, advanced compliance features, and more
  icon: "/assets/media/icons/security_64px_w.svg"

intro:
  title: Comprehensive security features
  ext_content: Open Distro for Elasticsearch Security provides you a comprehensive set of features to keep your data in the Elasticsearch cluster secure and stay compliant with regulations like GDPR, HIPAA, PCI, ISO and SOX. Whether you want to encrypt data at rest and in-transit, authenticate users against Active Directory, use Kerberos or JSON web tokens for single sign-on (SSO), or monitor and log any malicious access attempts, Open Distro for Elasticsearch Security has you covered.
  style: features feature-security-link

features:
  - title: Encryption
    content: Encryption in transit is essential to running a secure Elasticsearch cluster and Open Distro for Elasticsearch Security has you covered. Encryption in transit prevents with support for TLS 1.2 prevents unauthorized access to your while it is in-flight between nodes and clients, meeting stringent security and compliance requirements. 

  - title: Authentication
    content: With Open Distro for Elasticsearch Security, you can leverage your existing industry standard authentication techniques such as Kerberos, KDAP/Active Directory, JSON web tokens, TLS certificates, and Proxy authentication/SSO for user authentication.

  - title: Role-based access control
    content: Open Distro for Elasticsearch provides granular, role-based access, enabling you to control the actions a user can perform on your Elasticsearch cluster. Roles can be used to control cluster operations, access to indices, and even down to the fields and document level security. Additional Open Distro for Elasticsearch Security supports secure multi-tenant Elasticsearch clusters, where multiple teams can share the same cluster and be restricted to only access their own data and Kibana dashboards.  

  - title: Audit Logging
    content: Audit logging helps you remain compliant with government and industry regulations such as GDPR, HIPAA, PCI, and ISO. With audit logging, you can record and track all the actions taken users in your Elasticsearch cluster and monitor any suspicious activity.

featureList:
  title: Features
  sections:
    - content:
       - feature_item: "REST - and Transport Layer encryption"
       - feature_item: "Support for encryption at rest"
       - feature_item: "Role-based access control"
       - feature_item: "Index-Level security"
       - feature_item: "Internal/Native authentication"
       - feature_item: "HTTP Basic authentication"
       - feature_item: "Proxy & PKI authentication"
       - feature_item: "Pre-defined permission sets"
       - feature_item: "Single permissions"
       - feature_item: "Kibana Session Management"
       - feature_item: "Anonymous access"
       - feature_item: "Certificate Revocation Lists"
  
    - content:
       - feature_item: "Configuration hot-reload"
       - feature_item: "Cross Cluster Search support"
       - feature_item: "Active Directory"
       - feature_item: "LDAP"
       - feature_item: "Kerberos / SPNEGO"
       - feature_item: "JSON web token authentication"
       - feature_item: "SAML"
       - feature_item: "OpenID / JWKS"
       - feature_item: "Custom authenticators"
       - feature_item: "REST management API"
       - feature_item: "Document-level security"
       - feature_item: "Field-level security"
  
    - content:
       - feature_item: "Audit Logging"
       - feature_item: "Kibana SSO"
       - feature_item: "Kibana multitenancy"
       - feature_item: "Configuration GUI"
       - feature_item: "Read history audit logging"
       - feature_item: "Write history audit logging"
       - feature_item: "Field anonymization"
       - feature_item: "Immutable indices"
       - feature_item: "Event routing"
       - feature_item: "Elasticsearch installation monitoring"
       - feature_item: "Search Guard configuration monitoring"



